### ISSUE TITLE
Code is not working I keep getting these errors and my scripts are the exact same

### ISSUE THREAD

**Issue by thintheserverowner** [B-Ricey763/Roblox-Studio-Tycoon#1]
![image](https://user-images.githubusercontent.com/68404350/150678967-2c698f17-892e-458e-b5df-5e3c4cee152d.png)

**Comment by thintheserverowner** [comment]
video 1 btw

**Comment by B-Ricey763** [comment]
You have to actually follow the video for the scripts to work, they don't just magically work out of the box. Your error results from not watching the entire video and copy pasting the scripts.
